### ISSUE TITLE
Vavoo Live-Tv 1.3.2 Parser Apk

### ISSUE THREAD

**Issue by Fargo991** [Mastaaa1987/vxparser#1]
can you upload Vavoo Live Tv Parser apk please ? I don't know Pyhton Language so I dont use vxparser. Having an apk is a great convenience for those who do not understand the programming language very well.  That's why I ask you to reinstall the old apk versions.  If you install it, I will use it on Android TV.  Thanks a lot.

**Comment by Mastaaa1987** [comment]
Your Wisch is my Order ....
https://github.com/Mastaaa1987/vavoo-parser/releases

If you really intrest in the apk version of vxparser, i have build 90% of the new api into (tv ui friendly) version of Apk ...
I don't use the apk on my tv, even i don't now how about the apk really works, so far ...

**Comment by Fargo991** [comment]
> Your Wisch is my Order ....
> https://github.com/Mastaaa1987/vavoo-parser/releases
> 
> If you really intrest in the apk version of vxparser, i have build 90% of the new api into (tv ui friendly) version of Apk ...
> I don't use the apk on my tv, even i don't now how about the apk really works, so far ...

Thank you very much.

**Comment by Mastaaa1987** [comment]
Here look @ my first pre release of vxparser apk:
https://github.com/Mastaaa1987/vxparser/releases/tag/vxparser
It's a pre release at the moment, also it need some time on startup of the app ... (on app startup wait for the first log on main screen bevor make your choise what to do ...) & many little ui buggs in every corner but Main Screen are full functional & the search screen (2.) + settings working too!

Gerneral it work's so:
Hit Enter/OK  ----> to select/deselect/focus
Hit Back         -----> to unfocus (when on input or so ...)
When you are changed a input value it would be safed when you unfocus the input ...

Have fun with it!

Updates comming soon ...

**Comment by Fargo991** [comment]
> Here look @ my first pre release of vxparser apk:
> https://github.com/Mastaaa1987/vxparser/releases/tag/vxparser
> It's a pre release at the moment, also it need some time on startup of the app ... (on app startup wait for the first log on main screen bevor make your choise what to do ...) & many little ui buggs in every corner but Main Screen are full functional & the search screen (2.) + settings working too!
> 
> Gerneral it work's so:
> Hit Enter/OK  ----> to select/deselect/focus
> Hit Back         -----> to unfocus (when on input or so ...)
> When you are changed a input value it would be safed when you unfocus the input ...
> 
> Have fun with it!
> 
> Updates comming soon ... 
> 

Hello Mastaaa
What will we write Tivimate for all live tv channels , series and movies ?
For example I wrote 
http://192.168.1.165:8080/Turkey.m3u8
But Just Live Tv channels download. Not series and movies.

![Screenshot_2024-02-12-00-47-42-329_org.mastaaa.vxparser.jpg](https://github.com/Mastaaa1987/vxparser/assets/111020599/853d32fb-d20a-430f-b774-088cc48d438a)

![Screenshot_2024-02-12-00-48-01-954_org.mastaaa.vxparser.jpg](https://github.com/Mastaaa1987/vxparser/assets/111020599/552d696e-7584-408e-973e-e2f244525963)

![Uploading Screenshot_2024-02-12-00-48-20-411_org.mastaaa.vxparser.jpg …](![Screenshot_2024-02-12-00-47-21-530_org.mastaaa.vxparser.jpg](https://github.com/Mastaaa1987/vxparser/assets/111020599/f1473425-b6f4-475f-8e95-939a1a6542a3)

)

![Uploading Screenshot_2024-02-12-00-47-21-530_org.mastaaa.vxparser.jpg …]()

![Screenshot_2024-02-12-00-48-11-456_org.mastaaa.vxparser.jpg](https://github.com/Mastaaa1987/vxparser/assets/111020599/be52890d-ad11-4db5-b0ea-a5b207afe709)

![Screenshot_2024-02-12-00-47-07-706_org.mastaaa.vxparser.jpg](https://github.com/Mastaaa1987/vxparser/assets/111020599/5eceaa19-68c2-46a1-90ec-e5c24541c3c7)

**Comment by Mastaaa1987** [comment]
You must connect Tivimate via Xtream Code to Display VoD's on tivimate

Am So., 11. Feb. 2024 um 22:55 Uhr schrieb Fargo ***@***.***>:
