### ISSUE TITLE
vxparser als Service 

### ISSUE THREAD

**Issue by viruz82** [Mastaaa1987/vxparser#4]
Moin Mastaaa,

gibt's die Möglichkeit, das Ganze als Service auf einem Linux System automatisch beim Systemstart zu starten? Ich meine, du hattest das schon mal für eine frühere Version implementiert. Hier konnte ich jetzt nichts dazu finden.

**Comment by lapuertas** [comment]
besser wäre es   watch file zu machen   wenn das script offline geht

**Comment by viruz82** [comment]
Das eine schließt das andere ja nicht aus. Aber wenn ich meine Ubuntu VM durchstarte, hab ich keine Lust, das Script immer manuell zu starten. Daher wäre ein Service sehr cool.

**Comment by casaqori** [comment]
schau mal bitte ob vxparser/install.py im main branch was bringt
da wird ein service eingreichtet, aber ich habs nicht probiert

**Comment by Mastaaa1987** [comment]
Ja ich hab jetzt nicht wirklich viel gesagt aber wie casaqori richtig erkannt hat ist im vxparser verzeichniss die install.py welche unter unix systemen als root via python3 im vxparser verzeichniss zu starten ist... 
Ich muss aber ehrlich zu geben das ich die install.py quick & dirty in einer nacht runter geballert habe & da ich den vxparser nicht als service unter unix nutze sag ich mal 99% bug free xD
Ich bin z.b. davon aus gegangen das python3 python ist & deshalb ist in der install.py in der ersten zeile der interpreter schon falsch gesetzt wenn man z.b. raspberry nutzt wäre der fixx quick & dirty:
Zeile 1:
/usr/bin/python
zu ersetzten mit:
/usr/bin/python3

Aber sonst erstellt er so ne service datei die via systemctl enabled & gestartet wird ;-)
(Glaube aber der service heißt nicht vxparser sonder mxparser? oder so ... xD )

**Comment by viruz82** [comment]
Danke euch, mit python install.py lässt sich das Ding als Service installieren. Top. 👍🏼

**Comment by Mastaaa1987** [comment]
Quick & Dirty so wie ich das am liebsten hab :-D
